### PR TITLE
Fix spacing around generics with some composite type arguments

### LINKED ISSUE #171: Weird spacing around generics with composite type argument
The following example shows the buggy formatting.
```delphi
type
  A = TArray < set of byte >;
  B = TArray < array of A >;
```

[example in web demo](https://integrated-application-development.github.io/pasfmt/?source=dHlwZQogIEEgPSBUQXJyYXkgPHNldCBvZiBieXRlPjsKICBCID0gVEFycmF5IDxhcnJheSBvZiBBPjsK&settings=d3JhcF9jb2x1bW4gPSAxMjAKYmVnaW5fc3R5bGUgPSAiYXV0byIKZW5jb2RpbmcgPSAibmF0aXZlIgp1c2VfdGFicyA9IGZhbHNlCnRhYl93aWR0aCA9IDIKY29udGludWF0aW9uX2luZGVudHMgPSAyCmxpbmVfZW5kaW5nID0gIm5hdGl2ZSIK)

In this case I would expect no spaces around the `>` and `<` tokens:
```delphi
type
  A = TArray<set of byte>;
  B = TArray<array of A>;
```

This is probably just a bug in the generics consolidator
https://github.com/integrated-application-development/pasfmt/blob/292597848574d5043f31b217257eb855433f1dd2/core/src/rules/generics_consolidator.rs#L32-L46

That list needs `set` and `array` (any others?) added. 

Technically you can also declare an anonymous record as a generic type parameter, which would be difficult to handle because right now we do the generics consolidation before parsing.

### PR DESCRIPTION
**Pull request by zaneduffield**
Fixes #171.

I realised when fixing this that
```delphi
type A = B<string[10]>
```
was also a problem, and it only gets worse when you realise that the number can be any const expression:
```delphi
type A = B<string[10 + (1 shl 8) div 10 + SizeOf(C)]>
```

### CODE REVIEW

**Comment by zaneduffield** [comment]
There we go, got that 100% coverage on the patch 💯

File: core/src/rules/generics_consolidator.rs [hunk 1]
```diff
@@ -70,16 +88,46 @@ impl TokenConsolidator for DistinguishGenericTypeParamsConsolidator {
...
+                                brack_count -= 1;
+                                state.push(prev);
+                                break;
+                            }
+                        }
+                    }
+
+                    // support for expressions as the short string length: `A<string[1 shl 7]>`
+                    Some(TokenType::NumberLiteral(_) | TokenType::Op(_)) if brack_count > 0 => {}
+                    Some(TokenType::Keyword(kk)) if brack_count > 0 && kk.is_numeric_operator() => {
```
Comment (jgardn3r) [inline core/src/rules/generics_consolidator.rs:120]: This feels a little overly restrictive. Enter:
```delphi
type
  TFoo<T> = class end;
  Foo = TFoo<string[
    // this is the size of a thing
    sizeof(
    {$ifdef STR1}
    'asdf'
    {$else}
    'fsda'
    {$endif}
    )
  ]>;
```

**Review by jgardn3r — CHANGES_REQUESTED** [review]
Don't we just love this language we are dealing with? Effectively arbitrary complexity inside generics.

I'm also not sure how I feel about having a standalone commit "Update changelog", it isn't terribly desriptive. I would rather the changelog entries be inserted in each commit.

File: core/src/rules/generics_consolidator.rs (hunk 1 above)
Comment (zaneduffield) [reply core/src/rules/generics_consolidator.rs:120]: Is you point just that I should add `TextLiteral` to this? Conditional directives are included regardless of the bracket state.

Comment (jgardn3r) [reply core/src/rules/generics_consolidator.rs]: After looking a little closer at the list, the ones that are still excluded are: TextLiteral, Eof, Unknown, and some Keywords. Overall, I think yes adding TextLiteral would probably cover it.

File: core/src/lang.rs [hunk 2]
```diff
@@ -229,6 +229,19 @@ impl KeywordKind {
                 | KeywordKind::Stored
         )
     }
+
+    pub fn is_numeric_operator(&self) -> bool {
```
Comment (jgardn3r) [inline core/src/lang.rs:233]: Did you mean to remove the changelog entry for this?

File: core/src/rules/generics_consolidator.rs [hunk 3]
```diff
@@ -133,8 +184,19 @@ mod tests {
...
+    const SET: TokenType = TokenType::Keyword(KeywordKind::Set);
+    const ARRAY: TokenType = TokenType::Keyword(KeywordKind::Array);
+    const OF: TokenType = TokenType::Keyword(KeywordKind::Of);
     const CLASS: TokenType = TokenType::Keyword(KeywordKind::Class);
+    const REC: TokenType = TokenType::Keyword(KeywordKind::Record);
+    const CON: TokenType = TokenType::Keyword(KeywordKind::Constructor);
+
+    const NUM: TokenType = TokenType::NumberLiteral(NumberLiteralKind::Decimal);
+    const TEXT: TokenType = TokenType::TextLiteral(TextLiteralKind::SingleLine);
+    const MTEXT: TokenType = TokenType::TextLiteral(TextLiteralKind::SingleLine);
```
Comment (jgardn3r) [inline core/src/rules/generics_consolidator.rs:199]: Should this also be TLK::SingleLine?

**Review by jgardn3r — CHANGES_REQUESTED** [review]

File: core/src/rules/generics_consolidator.rs (hunk 3 above)
Comment (zaneduffield) [reply core/src/rules/generics_consolidator.rs:199]: haha, yes

File: core/src/lang.rs (hunk 2 above)
Comment (zaneduffield) [reply core/src/lang.rs:233]: Yes

Comment (jgardn3r) [reply core/src/lang.rs:233]: Why is that? It is part of the public API no?

Comment (zaneduffield) [reply core/src/lang.rs:233]: I read your comment as "did you mean to add..."

**Review by jgardn3r — APPROVED** [review]
Looks good
