### PR TITLE
Fix parsing of visibility specifiers outside type declarations

### LINKED ISSUE #211: Visibility specifiers treated as section keywords when outside type declaration
[example](https://integrated-application-development.github.io/pasfmt/?source=Y29uc3QKICBBdXRvbWF0ZWQgPSAwOwogIFByaXZhdGUgPSAwOwogIFByb3RlY3RlZCA9IDA7CiAgUHVibGljID0gMDsKICBQdWJsaXNoZWQgPSAwOw%3D%3D&settings=d3JhcF9jb2x1bW4gPSAxMjAKYmVnaW5fc3R5bGUgPSAiYXV0byIKZW5jb2RpbmcgPSAibmF0aXZlIgp1c2VfdGFicyA9IGZhbHNlCnRhYl93aWR0aCA9IDIKY29udGludWF0aW9uX2luZGVudHMgPSAyCmxpbmVfZW5kaW5nID0gIm5hdGl2ZSIK)

(copied here)
```delphi
const
  Automated = 0;
  Private = 0;
  Protected = 0;
  Public = 0;
  Published = 0;
```

is formatted to 
```delphi
const
Automated
  = 0;
Private
  = 0;
Protected
  = 0;
Public
  = 0;
Published
  = 0;
```

This is likely because each of these impure keywords start a new section inside a type declaration, and the parser isn't making sure that it's inside a type declaration before treating these like section headers.

### PR DESCRIPTION
**Pull request by zaneduffield**
Fixes #211.

- **Fix parsing of visibility specifiers outside type declarations**
- **Fix compiler errors in test for weird visibility consolidation cases**
    * This case was stressing a really wierd case where you can use the visibility specifiers as
      identifiers inside a type declaration, but it wasn't completely correct because it didn't
      declare the identifiers which it was referencing. I've confirmed that this example is actually
      allowed by Delphi.

### CODE REVIEW

File: core/src/defaults/parser/token_consolidation_tests.rs [hunk 1]
```diff
@@ -244,10 +244,14 @@ casing_token_consolidation_test!(
...
+                const
+                  &PROTECTED = False;
+                var
+                  &PRIVATE: integer;
                 property PUBLIC: integer read PRIVATE stored PROTECTED;
               automated
-              end"
-        },
+              end;
+        "},
```
Comment (jgardn3r) [inline core/src/defaults/parser/token_consolidation_tests.rs:254]: At least locally, the `"` goes at the end of the line.

**Review by jgardn3r — COMMENTED** [review]
Looking pretty good

File: core/src/defaults/parser.rs [hunk 2]
```diff
@@ -2178,34 +2185,39 @@ fn declaration_section(parser: &LLP) -> bool {
...
-                    | KK::Property
-                    | KK::Function
-                    | KK::Procedure
-                    | KK::Constructor
-                    | KK::Destructor
-                    | KK::End
-                    | KK::Implementation
-                    | KK::Initialization
-                    | KK::Finalization,
+                    | KK::Automated,
```
Comment (jgardn3r) [inline core/src/defaults/parser.rs:2220]: I love it when my comment get eaten by GitHub.

Would it make more sense and make this a bit cleaner to do something more like:
```suggestion
                (_, Some(TT::Keyword(kk) | TT::IdentifierOrKeyword(kk))) if matches!(kk, ...) => ... ,
```

Comment (jgardn3r) [reply core/src/defaults/parser.rs:2220]: The render is confused too it would seem.

Comment (zaneduffield) [reply core/src/defaults/parser.rs:2220]: Yeah good idea.

**Review by jgardn3r — APPROVED** [review]
