### PR TITLE
Fix formatting of `resourcestring` sections

### LINKED ISSUE #239: Formatting of resourcestring sections is incorrect.
Pasfmt 0.5.0 does not format `resourcestring` sections correctly. These should probably be formatted more like `const` sections.

To reproduce using the web demo, paste the following (expected output):
```
unit test;

resourcestring
  SFirst = 'test';
  SSecond = 'test';
  SThird = '''
multiple
lines
''';
```

Actual output as formatted by the web demo:
```
unit test;

resourcestring SFirst = 'test';
SSecond = 'test';
SThird = '''
multiple
lines
''';
```

A workaround is to surround the `resourcestring` section with format control comments to disable pasfmt, select the section and manually format it using the built-in formatter.

While I would obviously prefer to submit a patch/PR, unfortunately I don't know rust. Hopefully this is a simple fix.

### PR DESCRIPTION
**Pull request by zaneduffield**
- **Fix parsing of `resourcestring` sections**
- **Refactor declaration section parsing**

Fixes #239.

### CODE REVIEW

File: core/src/defaults/parser.rs [hunk 1]
```diff
@@ -2230,6 +2219,8 @@ fn declaration_section(parser: &LLP) -> bool {
             | KK::Initialization
             | KK::Finalization => true,
 
+            _ if kk.is_decl_section() => true,
```
Comment (jgardn3r) [inline core/src/defaults/parser.rs:2222]: I think this would make more sense as `_ => kk.is_decl_section(),`. It would also be more consistent with the other arm in this case.

File: core/src/defaults/parser.rs [hunk 2]
```diff
@@ -2263,21 +2254,13 @@ fn parse_exports(parser: &mut LLP) {
...
-                | KK::Begin
-                | KK::Asm
-                | KK::End
-                | KK::Function
-                | KK::Procedure
-        ))
-    )
+            KK::Exports | KK::Begin | KK::Asm | KK::End | KK::Function | KK::Procedure,
+        )) => true,
+        Some(TT::Keyword(kk)) if kk.is_decl_section() => true,
```
Comment (jgardn3r) [inline core/src/defaults/parser.rs:2261]: I think this would make more sense as `Some(TT::Keyword(kk)) => kk.is_decl_section(),`

**Review by jgardn3r — CHANGES_REQUESTED** [review]

**Review by jgardn3r — APPROVED** [review]
Looks good
