### PR TITLE
Fix formatting of comments before first item in import/export clauses.

### LINKED ISSUE #212: Strange block comment formatting on first unit in uses clause
[example](https://integrated-application-development.github.io/pasfmt/?source=Ly8gb25lIGNvbW1lbnQgb24gZmlyc3QgaXRlbSBpcyBhIGJpdCB3ZWlyZAp1c2VzCiAgeyBhIH0KICBBOwoKLy8gdHdvIGNvbW1lbnRzIGlzIGV2ZW4gd2VpcmRlcgp1c2VzCiAgeyBhIH0KICB7IGEgfSAKICBBOwoKLy8gbm8gcHJvYmxlbSB3aXRoIGNvbW1lbnRzIG9uIHRoZSBzZWNvbmQgaXRlbQp1c2VzCiAgQSwKICB7IGEgfQogIHsgYSB9IAogIEE7&settings=d3JhcF9jb2x1bW4gPSAxMjAKYmVnaW5fc3R5bGUgPSAiYXV0byIKZW5jb2RpbmcgPSAibmF0aXZlIgp1c2VfdGFicyA9IGZhbHNlCnRhYl93aWR0aCA9IDIKY29udGludWF0aW9uX2luZGVudHMgPSAyCmxpbmVfZW5kaW5nID0gIm5hdGl2ZSIK)

(copied here)
```delphi
// one comment on first item is a bit weird
uses
  { a }
  A;

// two comments is even weirder
uses
  { a }
  { a } 
  A;

// no problem with comments on the second item
uses
  A,
  { a }
  { a } 
  A;
``` 

is formatted to

```delphi
// one comment on first item is a bit weird
uses
  { a } A;

// two comments is even weirder
uses
  { a }
      { a } A;

// no problem with comments on the second item
uses
  A,
  { a }
  { a }
  A;
```

The input formatting is what I would expect as output.

From https://github.com/integrated-application-development/pasfmt/issues/193#issuecomment-2736784451.

### PR DESCRIPTION
**Pull request by zaneduffield**
Fixes #212.

### CODE REVIEW

**Comment by zaneduffield** [comment]
I removed the new line in `requirements.rs` because it was unreachable, and probably wouldn't even result in good formatting if it were reached.

It would handle the case where the parser has failed to put an 'individual' comment (one with a line break before it) on its own logical line, like in
```delphi
const
  {} A = 0;
```

With that extra line I added, it would force the break, but then it would think that the next token is 'continuing' the line, so it would probably result in something like
```delphi
const
  {}
      A = 0;
```

which is also buggy.

File: core/datatests/generators/logical_line_parser.rs [hunk 1]
```diff
@@ -3148,7 +3148,30 @@ mod regression {
...
+                _|exports
+                _|  {}
+                _|  A;
+                _|requires
+                _|  {}
+                _|  A;
+                _|contains
+                _|  {}
+                _|  A;
+            ",
```
Comment (jgardn3r) [inline core/datatests/generators/logical_line_parser.rs:3174]: I think this might make more sense in the the import and export tests.

File: core/datatests/generators/optimising_line_formatter.rs [hunk 2]
```diff
@@ -4545,6 +4545,62 @@ mod regression {
                 );
                 {$endif}
             ",
+            comment_between_import_and_unit_name = {
```
Comment (jgardn3r) [inline core/datatests/generators/optimising_line_formatter.rs:4548]: I think this might make more sense in the `comments` module.

File: core/src/defaults/parser.rs [hunk 3]
```diff
@@ -473,6 +473,7 @@ impl<'a, 'b> InternalDelphiLogicalLineParser<'a, 'b> {
                     self.finish_logical_line();
                     self.next_token(); // Exports
                     self.finish_logical_line();
+                    self.parse_comment_lines();
```
Comment (jgardn3r) [inline core/src/defaults/parser.rs:476]: In the other case, this line comes after pushing the `ImportExport` clause. Do you think these should be consistent?

**Review by jgardn3r — CHANGES_REQUESTED** [review]

**Review by jgardn3r — CHANGES_REQUESTED** [review]
I think, on the whole, I see the `regression` test module as weird cases that don't really fit into the other modules. In my mind, this case isn't weird enough.

File: core/src/defaults/parser.rs (hunk 3 above)
Comment (zaneduffield) [reply core/src/defaults/parser.rs:476]: Good point.

**Review by jgardn3r — APPROVED** [review]
