### PR TITLE
Inline `reference to procedure` and `reference to function`

### LINKED ISSUE #206: Unexpected break after `reference to`
When a method signature exceeds `wrap_column` then the formatter turns the parameters each into their own line - I don't particularly like that but I see the reasoning behind that.

However with the following code the behavior seems to be kinda inconsistent to the aforementioned behavior. The following code:

```
type
  Func<T1, T2, T3, TResult> = reference to function(const arg1: T1; const arg2: T2; const arg3: T3): TResult;

  Func<T1, T2, T3, T4, TResult> = reference to function(const arg1: T1; const arg2: T2; const arg3: T3; const arg4: T4): TResult;

  Func<T1, T2, T3, T4, T5, TResult> = reference to function(const arg1: T1; const arg2: T2; const arg3: T3; const arg4: T4; const arg5: T5): TResult;

  Func<T1, T2, T3, T4, T5, T6, TResult> = reference to function(const arg1: T1; const arg2: T2; const arg3: T3; const arg4: T4; const arg5: T5; const arg6: T6): TResult;

  Func<T1, T2, T3, T4, T5, T6, T7, TResult> = reference to function(const arg1: T1; const arg2: T2; const arg3: T3; const arg4: T4; const arg5: T5; const arg6: T6; const arg7: T7): TResult;
```

produces this:

```
type
  Func<T1, T2, T3, TResult> = reference to function(const arg1: T1; const arg2: T2; const arg3: T3): TResult;

  Func<T1, T2, T3, T4, TResult> =
    reference to function(const arg1: T1; const arg2: T2; const arg3: T3; const arg4: T4): TResult;

  Func<T1, T2, T3, T4, T5 TResult> =
    reference to function(const arg1: T1; const arg2: T2; const arg3: T3; const arg4: T4; const arg5: T5): TResult;

  Func<T1, T2, T3, T4, T5, T6, TResult> =
    reference to
      function(const arg1: T1; const arg2: T2; const arg3: T3; const arg4: T4; const arg5: T5; const arg6: T6): TResult;

  Func<T1, T2, T3, T4, T5, T6, T7, TResult> =
    reference to
      function(
        const arg1: T1;
        const arg2: T2;
        const arg3: T3;
        const arg4: T4;
        const arg5: T5;
        const arg6: T6;
        const arg7: T7
      ): TResult;
```

I can see why is probably does the line break after the `=` here first but the later line breaks look very unintuitive and one almost sees how the algorithm works and keeps inserting linebreaks. It still looks rather alien and not like any code style I have seen before.

### PR DESCRIPTION
**Pull request by jgardn3r**
This PR fixes #206

Additionally, this PR improves consistency across all routine headings. This includes procedural types and anonymous routine headings.

### CODE REVIEW

File: core/datatests/generators/optimising_line_formatter.rs [hunk 1]
```diff
@@ -1673,33 +1674,34 @@ mod type_decls {
...
-                              procedure(
-                                  AAAA: BBB
-                              );
-                      AAA =
-                          reference to
-                              procedure(
-                                  AA: B;
-                                  CC: D
-                              );
                 ",
```
Comment (zaneduffield) [inline core/datatests/generators/optimising_line_formatter.rs:1705]: I'm not sure what this case tests that the previous doesn't.

File: core/datatests/generators/optimising_line_formatter.rs [hunk 2]
```diff
@@ -1722,26 +1724,46 @@ mod type_decls {
...
+                              AA: B;
+                              CC: D
+                          ): BBBBBBB;
+                ",
+                function_reference_no_wrap = "
+                    // wrap_column=27          |
+                    type
+                      AA =
+                          reference to function;
                 ",
```
Comment (zaneduffield) [inline core/datatests/generators/optimising_line_formatter.rs:1767]: I'm not sure what this case tests that the previous doesn't.

File: core/src/rules/optimising_line_formatter/mod.rs [hunk 3]
```diff
@@ -994,13 +994,26 @@ impl<'this> InternalOptimisingLineFormatter<'this, '_> {
...
+                        .ctx_iter_indices()
+                        .find(|(_, ctx)| {
+                            matches!(
+                                ctx.context_type(),
+                                ContextType::AnonHeader | ContextType::Brackets(_, _)
+                            )
+                        })
+                        .is_none_or(|(_, ctx)| {
+                            !matches!(ctx.context_type(), ContextType::Brackets(_, _))
+                        }) =>
```
Comment (zaneduffield) [inline core/src/rules/optimising_line_formatter/mod.rs:1016]: This guard is pretty unwieldy now. Would you refactor it a bit?

**Review by zaneduffield — CHANGES_REQUESTED** [review]
Looking pretty good.

File: core/datatests/generators/optimising_line_formatter.rs (hunk 2 above)
Comment (jgardn3r) [reply core/datatests/generators/optimising_line_formatter.rs:1767]: By making the routine header break the line limit, it is showing that it will not break before the function.

File: core/datatests/generators/optimising_line_formatter.rs (hunk 1 above)
Comment (jgardn3r) [reply core/datatests/generators/optimising_line_formatter.rs:1705]: By making the routine header break the line limit, it is showing that it will not break before the procedure.

**Review by zaneduffield — APPROVED** [review]
👍
